### ISSUE TITLE
gitlab template 

### ISSUE THREAD

**Issue by lavvy** [rancher/rancher-catalog#50]
We have got Jenkins template in catalog ,  i think it would be cool to have a mature source code management platform like gitlab too in catalog

**Comment by ColtonProvias** [comment]
I have GitLab running on my server along with GitLab runner, so maybe this might be a good starting point:

```yaml
GitLab:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gitlab/gitlab-ce:latest
  volumes:
  - /opt/gitlab/config:/etc/gitlab
  - /opt/gitlab/logs:/var/log/gitlab
  - /opt/gitlab/data:/var/opt/gitlab
  stdin_open: true

GitLab-Runner:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gitlab/gitlab-runner:latest
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /opt/gitlab-runner/config:/etc/gitlab-runner
  - /etc/docker:/etc/docker
  stdin_open: true
  links:
  - GitLab:GitLab
```

Note that GitLab exposes the ports 22, 80, and 443.   Thus I have port 22 exposed publicly on another port for SSH access; the others operate behind load balancers.
